---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.13.37
  

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[terraform-wrapper::default]
    attributes:

transport:
   name: sftp

verifier:
   name: inspec
